package easy._389;

import java.util.Arrays;

/**
 * @author zly
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

public class FindTheDifference {

    public char findTheDifference(String s, String t) {

        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();
        Arrays.sort(sArray);
        Arrays.sort(tArray);

        for (int i = 0; i < s.length(); i ++) if (sArray[i] != tArray[i]) return tArray[i];

        return tArray[tArray.length - 1];

    }

}
